/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as BackgroundRemoverRouteImport } from './routes/background-remover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GeminiVideoWatermarkRemoverRouteImport } from './routes/gemini-video-watermark-remover'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PdfWatermarkRemoverRouteImport } from './routes/pdf-watermark-remover'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UpscaleRouteImport } from './routes/upscale'
import { Route as VideoEnhancerRouteImport } from './routes/video-enhancer'
import { Route as RemoveImageRouteImport } from './routes/remove.image'
import { Route as RemoveVideoRouteImport } from './routes/remove.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRemoverRoute = BackgroundRemoverRouteImport.update({
  id: '/background-remover',
  path: '/background-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GeminiVideoWatermarkRemoverRoute =
  GeminiVideoWatermarkRemoverRouteImport.update({
    id: '/gemini-video-watermark-remover',
    path: '/gemini-video-watermark-remover',
    getParentRoute: () => rootRouteImport,
  } as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfWatermarkRemoverRoute = PdfWatermarkRemoverRouteImport.update({
  id: '/pdf-watermark-remover',
  path: '/pdf-watermark-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UpscaleRoute = UpscaleRouteImport.update({
  id: '/upscale',
  path: '/upscale',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoEnhancerRoute = VideoEnhancerRouteImport.update({
  id: '/video-enhancer',
  path: '/video-enhancer',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveImageRoute = RemoveImageRouteImport.update({
  id: '/remove/image',
  path: '/remove/image',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveVideoRoute = RemoveVideoRouteImport.update({
  id: '/remove/video',
  path: '/remove/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/api-reference': typeof ApiReferenceRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/gemini-video-watermark-remover': typeof GeminiVideoWatermarkRemoverRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pdf-watermark-remover': typeof PdfWatermarkRemoverRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/upscale': typeof UpscaleRoute
  '/video-enhancer': typeof VideoEnhancerRoute
  '/remove/image': typeof RemoveImageRoute
  '/remove/video': typeof RemoveVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/api-reference': typeof ApiReferenceRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/gemini-video-watermark-remover': typeof GeminiVideoWatermarkRemoverRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pdf-watermark-remover': typeof PdfWatermarkRemoverRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/upscale': typeof UpscaleRoute
  '/video-enhancer': typeof VideoEnhancerRoute
  '/remove/image': typeof RemoveImageRoute
  '/remove/video': typeof RemoveVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/api-reference': typeof ApiReferenceRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/gemini-video-watermark-remover': typeof GeminiVideoWatermarkRemoverRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pdf-watermark-remover': typeof PdfWatermarkRemoverRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/upscale': typeof UpscaleRoute
  '/video-enhancer': typeof VideoEnhancerRoute
  '/remove/image': typeof RemoveImageRoute
  '/remove/video': typeof RemoveVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/api-reference'
    | '/background-remover'
    | '/contact'
    | '/faq'
    | '/features'
    | '/gemini-video-watermark-remover'
    | '/history'
    | '/how-it-works'
    | '/pdf-watermark-remover'
    | '/pricing'
    | '/tools'
    | '/upscale'
    | '/video-enhancer'
    | '/remove/image'
    | '/remove/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/api-reference'
    | '/background-remover'
    | '/contact'
    | '/faq'
    | '/features'
    | '/gemini-video-watermark-remover'
    | '/history'
    | '/how-it-works'
    | '/pdf-watermark-remover'
    | '/pricing'
    | '/tools'
    | '/upscale'
    | '/video-enhancer'
    | '/remove/image'
    | '/remove/video'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate'
    | '/api-reference'
    | '/background-remover'
    | '/contact'
    | '/faq'
    | '/features'
    | '/gemini-video-watermark-remover'
    | '/history'
    | '/how-it-works'
    | '/pdf-watermark-remover'
    | '/pricing'
    | '/tools'
    | '/upscale'
    | '/video-enhancer'
    | '/remove/image'
    | '/remove/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  BackgroundRemoverRoute: typeof BackgroundRemoverRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  GeminiVideoWatermarkRemoverRoute: typeof GeminiVideoWatermarkRemoverRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PdfWatermarkRemoverRoute: typeof PdfWatermarkRemoverRoute
  PricingRoute: typeof PricingRoute
  ToolsRoute: typeof ToolsRoute
  UpscaleRoute: typeof UpscaleRoute
  VideoEnhancerRoute: typeof VideoEnhancerRoute
  RemoveImageRoute: typeof RemoveImageRoute
  RemoveVideoRoute: typeof RemoveVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-remover': {
      id: '/background-remover'
      path: '/background-remover'
      fullPath: '/background-remover'
      preLoaderRoute: typeof BackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemini-video-watermark-remover': {
      id: '/gemini-video-watermark-remover'
      path: '/gemini-video-watermark-remover'
      fullPath: '/gemini-video-watermark-remover'
      preLoaderRoute: typeof GeminiVideoWatermarkRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-watermark-remover': {
      id: '/pdf-watermark-remover'
      path: '/pdf-watermark-remover'
      fullPath: '/pdf-watermark-remover'
      preLoaderRoute: typeof PdfWatermarkRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upscale': {
      id: '/upscale'
      path: '/upscale'
      fullPath: '/upscale'
      preLoaderRoute: typeof UpscaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-enhancer': {
      id: '/video-enhancer'
      path: '/video-enhancer'
      fullPath: '/video-enhancer'
      preLoaderRoute: typeof VideoEnhancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove/image': {
      id: '/remove/image'
      path: '/remove/image'
      fullPath: '/remove/image'
      preLoaderRoute: typeof RemoveImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove/video': {
      id: '/remove/video'
      path: '/remove/video'
      fullPath: '/remove/video'
      preLoaderRoute: typeof RemoveVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  BackgroundRemoverRoute: BackgroundRemoverRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  GeminiVideoWatermarkRemoverRoute: GeminiVideoWatermarkRemoverRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  PdfWatermarkRemoverRoute: PdfWatermarkRemoverRoute,
  PricingRoute: PricingRoute,
  ToolsRoute: ToolsRoute,
  UpscaleRoute: UpscaleRoute,
  VideoEnhancerRoute: VideoEnhancerRoute,
  RemoveImageRoute: RemoveImageRoute,
  RemoveVideoRoute: RemoveVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
